// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boktwgksctowdzwjhcgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJva3R3Z2tzY3Rvd2R6d2poY2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzMwMTEsImV4cCI6MjA2MDg0OTAxMX0.PaHwx49rPR0z0D-W4_zO0sT6nMIDiMYfC3D03rCMpIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);